# Generated by Django 3.1.7 on 2021-04-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bmi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='weight',
            field=models.FloatField(),
        ),
    ]
